format = """
$directory \
$git_branch \
$git_status
$character"""

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = "…/"
format = "[$path]($style) "

[git_branch]
symbol = ""
style = "bold purple"
format = "[$symbol $branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

